---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-assessment-tool
      vars:
        archive_url: https://github.com/eladshamir/Internal-Monologue/tarball/master/
        install_dir: /tools/Internal-Monologue
        mono: yes
