---
# These tools are used by the ansible.builtin.pip module below
- name: Install virtualenv
  ansible.builtin.package:
    name:
      - virtualenv

- name: Create the virtualenv
  ansible.builtin.pip:
    chdir: "{{ assessment_tool_install_dir }}"
    extra_args: "{{ assessment_tool_pip_extra_args | default(omit) }}"
    name: "{{ assessment_tool_pip_packages | default(omit) }}"
    requirements: "{{ assessment_tool_pip_requirements_file | default(omit) }}"
    virtualenv: "{{ assessment_tool_virtualenv_dir | default((assessment_tool_install_dir, '.venv') | path_join) }}"
    virtualenv_python: "{{ (assessment_tool_python2) | ternary('/usr/bin/python2', omit) }}"
