---
# These tools are used by the ansible.builtin.pip module below
- name: Install virtualenv
  block:
    - name: Install virtualenv via the package manager
      ansible.builtin.package:
        name:
          - virtualenv
      when: not assessment_tool_python2

    - name: Install virtualenv via pip
      ansible.builtin.pip:
        name:
          # virtualenv 20.22.0 removed support for creating Python 2
          # venvs:
          # https://virtualenv.pypa.io/en/latest/changelog.html#v20-22-0-2023-04-19
          - virtualenv<20.22.0
      when: assessment_tool_python2

- name: Create the virtualenv
  ansible.builtin.pip:
    chdir: "{{ assessment_tool_install_dir }}"
    extra_args: "{{ assessment_tool_pip_extra_args | default(omit) }}"
    name: "{{ assessment_tool_pip_packages | default(omit) }}"
    requirements: "{{ assessment_tool_pip_requirements_file | default(omit) }}"
    virtualenv: "{{ assessment_tool_virtualenv_dir | default((assessment_tool_install_dir, '.venv') | path_join) }}"
    virtualenv_python: "{{ (assessment_tool_python2) | ternary('/usr/bin/python2', omit) }}"
