---
# These tools are used by the ansible.builtin.pip module below
- name: Install virtualenv
  ansible.builtin.package:
    name:
      - virtualenv

- name: Create the virtualenv
  ansible.builtin.pip:
    chdir: "{{ install_dir }}"
    name: "{{ pip_packages | default(omit) }}"
    requirements: "{{ pip_requirements_file | default(omit) }}"
    virtualenv: "{{ virtualenv_dir | default((install_dir, '.venv') | path_join) }}"
