---
# These tools are used by the ansible.builtin.unarchive module below
- name: Install tar and zip
  ansible.builtin.package:
    name:
      - tar
      - unzip
      - zip

- name: Download the tool archive from {{ assessment_tool_archive_src }}
  ansible.builtin.get_url:
    dest: "{{ assessment_tool_install_dir }}"
    headers: >-
      {{ assessment_tool_custom_headers
      if assessment_tool_custom_headers is defined
      else omit }}
    mode: u=rw,g=rw,o=rw
    url: "{{ assessment_tool_archive_src }}"
  register: download

- name: Unarchive the tool
  ansible.builtin.unarchive:
    dest: "{{ assessment_tool_install_dir }}"
    extra_opts: "{{ assessment_tool_unarchive_extra_opts | default(omit) }}"
    group: "{{ assessment_tool_group }}"
    remote_src: true
    src: "{{ download.dest }}"
