---
# These tools are used by the ansible.builtin.unarchive module below
- name: Install tar and zip
  ansible.builtin.package:
    name:
      - tar
      - unzip
      - zip

- name: Install the tool from {{ archive_src }}
  ansible.builtin.unarchive:
    dest: "{{ install_dir }}"
    extra_opts:
      - "--strip-components=1"
    group: "{{ group }}"
    remote_src: yes
    src: "{{ archive_src }}"
