---
# TODO:  Revert this equivs foo.  See #71 for more details.
#
# Debian Trixie has libicu76, but the deb package generated for
# PowerShell/PowerShell only supports libicu74 for now.  This is the
# case even though PowerShell/PowerShell functions fine with libicu76.
# See PowerShell/PowerShell#25865 for more information.
#
# Until a new release is created, we use Debian's equivs package to
# install a dummy dependency for libicu74, which is sufficient to
# install PowerShell/PowerShell.  When run, PowerShell/PowerShell will
# use the libicu76 dependency installed from the official Debian
# Trixie package repository.
- name: Build and install equivs dummy package for libicu74 for Trixie
  when:
    - ansible_distribution_release in ["trixie"]
  block:
    - name: Install equivs and libicu76
      ansible.builtin.package:
        name:
          - equivs
          - libicu76

    - name: Copy dummy control file for libicu74
      ansible.builtin.copy:
        dest: /tmp/libicu74.equivs
        group: root
        mode: u=rw,g=rw,o=r
        owner: root
        src: libicu74.equivs

    - name: Build dummy libicu74 deb package
      ansible.builtin.command:
        argv:
          - equivs-build
          - libicu74.equivs
        chdir: /tmp
        creates: /tmp/libicu74_74_all.deb

    - name: Install dummy libicu74 deb package
      ansible.builtin.apt:
        deb: /tmp/libicu74_74_all.deb

- name: Install PowerShell if necessary
  ansible.builtin.apt:
    deb: "{{ powershell_package_name }}"
