---
- name: Install Python and Pip
  block:
    - name: Install Python
      ansible.builtin.include_role:
        name: python
      vars:
        python_install_python2: "{{ assessment_tool_python2 }}"
        python_install_development_dependencies: "{{ assessment_tool_python_install_development_dependencies }}"
    - name: Install Pip
      ansible.builtin.include_role:
        name: pip
      vars:
        pip_install_pip2: "{{ assessment_tool_python2 }}"
