---
# These tools are used by the ansible.builtin.unarchive module below
- name: Install tar and zip
  ansible.builtin.package:
    name:
      - tar
      - unzip
      - zip

- name: Install the tool from {{ archive_src }}
  ansible.builtin.unarchive:
    dest: "{{ install_dir }}"
    extra_opts: "{{ unarchive_extra_opts | default(omit) }}"
    group: "{{ group }}"
    remote_src: yes
    src: "{{ archive_src }}"
  tags:
    # The Ubuntu Focal version of the golang package is pretty old,
    # and there is no newer version in backports.  When we build a
    # project via go build, that version modifies or adds some files
    # that cause this task to fail when idempotence runs.
    - molecule-idempotence-notest
