---
- name: Install Go toolchain and Git (Debian Buster and Ubuntu Bionic)
  ansible.builtin.package:
    name:
      # Third-party Go packages are often installed via git
      - git
      - golang
    default_release: "{{ ansible_distribution_release }}-backports"
  when:
    - (ansible_distribution == "Debian" and ansible_distribution_release == "buster") or (ansible_distribution == "Ubuntu" and ansible_distribution_release == "bionic")

- name: Install Go toolchain and Git (not Debian Buster or Ubuntu Bionic)
  ansible.builtin.package:
    name:
      # Third-party Go packages are often installed via git
      - git
      - golang
  when:
    - not ((ansible_distribution == "Debian" and ansible_distribution_release == "buster") or (ansible_distribution == "Ubuntu" and ansible_distribution_release == "bionic"))
