---
- name: Install cargo
  ansible.builtin.package:
    name:
      - cargo

- name: Install cargo packages
  community.general.cargo:
    name: "{{ assessment_tool_cargo_packages }}"
    path: "{{ assessment_tool_cargo_install_dir | default(assessment_tool_install_dir) }}"
  when:
    - assessment_tool_cargo_packages is defined

- name: Build cargo tool
  ansible.builtin.command:
    chdir: "{{ assessment_tool_install_dir }}"
    # The version of cargo on Kali and Debian 12 (Bookworm) does not
    # support the --profile option without -Z unstable-options;
    # furthermore, there is no long option equivalent for -Z.
    cmd: >
      /usr/bin/cargo build -Z unstable-options
      --profile={{ assessment_tool_cargo_profile }}
    creates: "{{ assessment_tool_install_dir }}/target/{{ assessment_tool_cargo_profile }}/{{ assessment_tool_install_dir | basename }}"
  when:
    - assessment_tool_cargo_build
