---
- name: Install Go toolchain
  block:
    - name: Install Go toolchain (Debian Buster or Bullseye)
      when:
        - ansible_distribution == "Debian"
        - ansible_distribution_release in ["buster", "bullseye"]
      block:
        - name: Setup backports (Debian Buster or Bullseye)
          ansible.builtin.include_role:
            name: backports
        - name: Install Go toolchain and Git (Debian Buster or Bullseye)
          ansible.builtin.package:
            default_release: "{{ ansible_distribution_release }}-backports"
            name:
              # Third-party Go packages are often installed via git
              - git
              - golang

    - name: Install Go toolchain and Git (not Debian Buster or Bullseye)
      ansible.builtin.package:
        name:
          # Third-party Go packages are often installed via git
          - git
          - golang
      when:
        - not (ansible_distribution == "Debian" and ansible_distribution_release in ["buster", "bullseye"])
