---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Create the directory {{ install_dir }}
  ansible.builtin.file:
    group: "{{ group }}"
    mode: "{{ mode }}"
    owner: "{{ owner }}"
    path: "{{ install_dir }}"
    state: directory

- name: Install the tool if necessary
  ansible.builtin.include_tasks: install_tool.yml
  when:
    - archive_src is defined

- name: Install Go toolchain if necessary
  ansible.builtin.include_tasks: install_go.yml
  when:
    - go

- name: Build Go project if necessary
  ansible.builtin.include_tasks: build_go_tool.yml
  when:
    - go
    - go_build

- name: Install mono if necessary
  ansible.builtin.include_tasks: install_mono.yml
  when:
    - csharp

# There are Python tools that require a Rust compiler to build the
# compiled portion of the tool, so it makes sense to install cargo and
# a Rust compiler before installing the Python tool.
- name: Install Rust toolchain if necessary
  ansible.builtin.include_tasks: install_rust.yml
  when:
    - rust or cargo_packages is defined

- name: Install Python 2 if necessary
  ansible.builtin.include_tasks: install_python2.yml
  when:
    - python2

- name: Create a Python virtualenv if necessary
  ansible.builtin.include_tasks: create_python_venv.yml
  when:
    - pip_packages is defined or pip_requirements_file is defined

- name: Install PowerShell if necessary
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - install_powershell_{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml
        - install_powershell_{{ ansible_distribution }}.yml
        - install_powershell_{{ ansible_os_family }}.yml
      paths:
        - "{{ role_path }}/tasks"
  when:
    - powershell

- name: >-
    Ensure that the contents of the install directory have the correct
    user and group ownership
  ansible.builtin.file:
    group: "{{ group }}"
    owner: "{{ owner }}"
    path: "{{ install_dir }}"
    recurse: yes
    state: directory
