---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Create the directory {{ assessment_tool_install_dir }}
  ansible.builtin.file:
    group: "{{ assessment_tool_group }}"
    mode: "{{ assessment_tool_mode }}"
    owner: "{{ assessment_tool_owner }}"
    path: "{{ assessment_tool_install_dir }}"
    state: directory

- name: Install the tool if necessary
  ansible.builtin.include_tasks: install_tool.yml
  when:
    - assessment_tool_archive_src is defined

- name: Install Go toolchain if necessary
  ansible.builtin.include_tasks: install_go.yml
  when:
    - assessment_tool_go

- name: Build Go project if necessary
  ansible.builtin.include_tasks: build_go_tool.yml
  when:
    - assessment_tool_go
    - assessment_tool_go_build

- name: Install mono if necessary
  ansible.builtin.include_tasks: install_mono.yml
  when:
    - assessment_tool_csharp

# There are Python tools that require a Rust compiler to build the
# compiled portion of the tool, so it makes sense to install cargo
# (which has a Rust compiler as a dependency) before installing the
# Python tool.
- name: Install Rust toolchain if necessary
  ansible.builtin.include_tasks: install_rust.yml
  when:
    - assessment_tool_rust or assessment_tool_cargo_packages is defined

- name: Install Python and create Python virtualenv
  when:
    - assessment_tool_pip_packages is defined or assessment_tool_pip_requirements_file is defined
  block:
    - name: Install Python if necessary
      ansible.builtin.include_tasks: install_python.yml

    - name: Create a Python virtualenv if necessary
      ansible.builtin.include_tasks: create_python_venv.yml

- name: Install PowerShell if necessary
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - install_powershell_{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml
        - install_powershell_{{ ansible_distribution }}.yml
        - install_powershell_{{ ansible_os_family }}.yml
      paths:
        - "{{ role_path }}/tasks"
  when:
    - assessment_tool_powershell

- name: >-
    Ensure that the contents of the install directory have the correct
    user and group ownership
  ansible.builtin.file:
    group: "{{ assessment_tool_group }}"
    owner: "{{ assessment_tool_owner }}"
    path: "{{ assessment_tool_install_dir }}"
    recurse: yes
    state: directory
