---
- name: backports
  src: https://github.com/cisagov/ansible-role-backports
- name: pip
  src: https://github.com/cisagov/ansible-role-pip
- name: python
  src: https://github.com/cisagov/ansible-role-python
  version: improvement/add-role-var-for-installing-dev-dependencies
