---
- name: Converge
  hosts: all
  tasks:
    - name: Install PowerUpSQL and powershell
      ansible.builtin.include_role:
        name: ansible-role-assessment-tool
      vars:
        archive_src: https://github.com/NetSPI/PowerUpSQL/tarball/master
        install_dir: /tools/PowerUpSQL
        powershell: yes
        unarchive_extra_opts:
          - --strip-components=1
