---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # This Ansible role only supports Debian-based platforms for now.
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: docker.io/geerlingguy/docker-amazonlinux2023-ansible:latest
  #   name: amazonlinux2023-systemd-amd64
  #   platform: amd64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: docker.io/geerlingguy/docker-amazonlinux2023-ansible:latest
  #   name: amazonlinux2023-systemd-arm64
  #   platform: arm64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: docker.io/geerlingguy/docker-debian10-ansible:latest
    name: debian10-systemd-amd64
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # PowerShell does not support ARM64 on Debian.
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: docker.io/geerlingguy/docker-debian10-ansible:latest
  #   name: debian10-systemd-arm64
  #   platform: arm64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: docker.io/geerlingguy/docker-debian11-ansible:latest
    name: debian11-systemd-amd64
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # PowerShell does not support ARM64 on Debian.
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: docker.io/geerlingguy/docker-debian11-ansible:latest
  #   name: debian11-systemd-arm64
  #   platform: arm64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: docker.io/geerlingguy/docker-debian12-ansible:latest
    name: debian12-systemd-amd64
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # PowerShell does not support ARM64 on Debian.
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: docker.io/geerlingguy/docker-debian12-ansible:latest
  #   name: debian12-systemd-arm64
  #   platform: arm64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: docker.io/cisagov/docker-debian13-ansible:latest
    name: debian13-systemd-amd64
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: docker.io/cisagov/docker-debian13-ansible:latest
  #   name: debian13-systemd-arm64
  #   platform: arm64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # Kali Linux offers its own PowerShell system package...
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: docker.io/cisagov/docker-kali-ansible:latest
    name: kali-systemd-amd64
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # ...but not for ARM64
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: docker.io/cisagov/docker-kali-ansible:latest
  #   name: kali-systemd-arm64
  #   platform: arm64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # This Ansible role only supports Debian-based platforms for now.
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: docker.io/geerlingguy/docker-fedora39-ansible:latest
  #   name: fedora39-systemd-amd64
  #   platform: amd64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: docker.io/geerlingguy/docker-fedora39-ansible:latest
  #   name: fedora39-systemd-arm64
  #   platform: arm64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: docker.io/geerlingguy/docker-fedora40-ansible:latest
  #   name: fedora40-systemd-amd64
  #   platform: amd64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: docker.io/geerlingguy/docker-fedora40-ansible:latest
  #   name: fedora40-systemd-arm64
  #   platform: arm64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # PowerShell does not support ARM64 on Ubuntu.
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible:latest
    name: ubuntu-20-systemd-amd64
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # PowerShell does not support ARM64 on Ubuntu.
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: docker.io/geerlingguy/docker-ubuntu2004-ansible:latest
  #   name: ubuntu-20-systemd-arm64
  #   platform: arm64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - cgroupns_mode: host
    command: /lib/systemd/systemd
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    name: ubuntu-22-systemd-amd64
    platform: amd64
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # PowerShell does not support ARM64 on Ubuntu.
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
  #   name: ubuntu-22-systemd-arm64
  #   platform: arm64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # The latest official release of PowerShell does not support Ubuntu
  # Noble.  It requires libicu <= 72, but Noble only offers libicu 74:
  # https://packages.ubuntu.com/search?keywords=libicu&searchon=names&suite=noble&section=all
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: docker.io/geerlingguy/docker-ubuntu2404-ansible:latest
  #   name: ubuntu-24-systemd-amd64
  #   platform: amd64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  # PowerShell does not support ARM64 on Ubuntu.
  # - cgroupns_mode: host
  #   command: /lib/systemd/systemd
  #   image: docker.io/geerlingguy/docker-ubuntu2404-ansible:latest
  #   name: ubuntu-24-systemd-arm64
  #   platform: arm64
  #   pre_build_image: true
  #   privileged: true
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
scenario:
  name: powershell
verifier:
  name: testinfra
