---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-assessment-tool
      vars:
        archive_url: https://github.com/bovine/datapipe/tarball/master
        install_dir: /tools/datapipe
