---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-assessment-tool
      vars:
        archive_src: "https://github.com/michenriksen/aquatone/\
        releases/download/v1.7.0/aquatone_linux_amd64_1.7.0.zip"
        install_dir: /tools/aquatone
    - role: ansible-role-assessment-tool
      vars:
        archive_src: https://github.com/bovine/datapipe/tarball/master
        install_dir: /tools/datapipe
        unarchive_extra_opts:
          - --strip-components=1
