---
- name: Converge
  hosts: all
  tasks:
    - name: Install Internal Monologue and the C# toolchain
      # We do prepend the name of the role to the role variables, but
      # Molecule does its own role discovery with inconsistent naming.
      # This is the reason for the noqa below.
      ansible.builtin.include_role: # noqa var-naming[no-role-prefix]
        name: ansible-role-assessment-tool
      vars:
        assessment_tool_archive_src: https://github.com/eladshamir/Internal-Monologue/tarball/master/
        assessment_tool_csharp: yes
        assessment_tool_install_dir: /tools/Internal-Monologue
        assessment_tool_unarchive_extra_opts:
          - --strip-components=1
