---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-assessment-tool
      vars:
        archive_src: https://github.com/eladshamir/Internal-Monologue/tarball/master/
        csharp: yes
        install_dir: /tools/Internal-Monologue
        unarchive_extra_opts:
          - --strip-components=1
