---
- name: Converge
  hosts: all
  tasks:
    - name: Install Internal Monologue and the C# toolchain
      ansible.builtin.include_role:
        name: ansible-role-assessment-tool
      vars:
        archive_src: https://github.com/eladshamir/Internal-Monologue/tarball/master/
        csharp: yes
        install_dir: /tools/Internal-Monologue
        unarchive_extra_opts:
          - --strip-components=1
