---
- name: Converge
  hosts: all
  tasks:
    - name: Install RustScan
      ansible.builtin.include_role:
        name: ansible-role-assessment-tool
      vars:
        archive_src: https://github.com/RustScan/RustScan/tarball/master
        # We lowercase the install directory name so it matches the
        # name in the cargo toml file, which is in turn used to
        # determine the name of the build product in
        # tasks/install_rust.yml.
        install_dir: /tools/rustscan
        rust: yes
        unarchive_extra_opts:
          - --strip-components=1
