---
# This molecule configuration file is suitable for testing Ansible
# roles that _do not_ require SystemD.  If your Ansible role _does_
# require SystemD then you should use molecule-with-systemd.yml
# instead.
#
# Note that the molecule configuration file that is symlinked to
# molecule.yml is the one that will be used.
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  # This Ansible role only supports Debian-based platforms for now.
  # - image: amazonlinux:2023
  #   name: amazonlinux2023
  #   platform: amd64
  # Debian Buster does not have a new enough version of cargo to parse
  # the cargo.toml file for RustScan.  There is no newer version in
  # backports.
  # - image: debian:buster-slim
  #   name: debian10
  #   platform: amd64
  # Debian Bullseye has an older version of cargo, which gives a
  # "feature `resolver` is required" error when installing RustScan.
  # There is no newer version in backports.
  # - image: debian:bullseye-slim
  #   name: debian11
  #   platform: amd64
  - image: debian:bookworm-slim
    name: debian12
    platform: amd64
  - image: kalilinux/kali-rolling
    name: kali
    platform: amd64
  # This Ansible role only supports Debian-based platforms for now.
  # - image: fedora:37
  #   name: fedora37
  #   platform: amd64
  # - image: fedora:38
  #   name: fedora38
  #   platform: amd64
  - image: ubuntu:focal
    name: ubuntu20
    platform: amd64
  - image: ubuntu:jammy
    name: ubuntu22
    platform: amd64
scenario:
  name: rust
verifier:
  name: testinfra
