---
- name: Converge
  hosts: all
  tasks:
    - name: Install Auto-Egress-Assess in a venv via pipenv
      block:
        # After version 1.0.0 this tool requires Python 3.13 or newer
        - name: >-
            Determine the version of Auto-Egress-Assess that should be
            installed
          block:
            - name: Set the version for Python<3.13
              ansible.builtin.set_fact:
                aea_version: v1.0.0
              when:
                - ansible_python_version is ansible.builtin.version("3.13", "<")

            - name: Set the version for Python>=3.13
              ansible.builtin.set_fact:
                aea_version: main
              when:
                - ansible_python_version is ansible.builtin.version("3.13", ">=")

        - name: Install Auto-Egress-Assess in a venv via pipenv
          # We do prepend the name of the role to the role variables,
          # but Molecule does its own role discovery with inconsistent
          # naming.  This is the reason for the noqa below.
          ansible.builtin.include_role: # noqa var-naming[no-role-prefix]
            name: ansible-role-assessment-tool
          vars:
            assessment_tool_archive_src: >-
              https://github.com/tarrell13/Auto-Egress-Assess/tarball/{{
              aea_version }}
            assessment_tool_install_dir: /tools/Auto-Egress-Assess
            assessment_tool_pipenv: true
            assessment_tool_unarchive_extra_opts:
              - --strip-components=1

    - name: Install sshenum and a pip package in a venv
      # We do prepend the name of the role to the role variables, but
      # Molecule does its own role discovery with inconsistent naming.
      # This is the reason for the noqa below.
      ansible.builtin.include_role: # noqa var-naming[no-role-prefix]
        name: ansible-role-assessment-tool
      vars:
        assessment_tool_archive_src: https://github.com/MacR6/sshenum/tarball/master
        assessment_tool_install_dir: /tools/sshenum
        assessment_tool_pip_packages:
          - paramiko
        assessment_tool_unarchive_extra_opts:
          - --strip-components=1

    # yamllint/ansible-lint complain about a long line in this
    # comment, but there is nothing I can do to shorten it.
    #
    # yamllint disable rule:line-length
    # It would be nice to test this case, but pip install . is not
    # idempotent.
    # - name: Install Hasher in a venv
    #   # We do prepend the name of the role to the role variables, but
    #   # Molecule does its own role discovery with inconsistent naming.
    #   # This is the reason for the noqa below.
    #   ansible.builtin.include_role: # noqa var-naming[no-role-prefix]
    #     name: ansible-role-assessment-tool
    #   vars:
    #     assessment_tool_archive_src: https://github.com/FortyNorthSecurity/Hasher/tarball/master
    #     assessment_tool_install_dir: /tools/Hasher
    #     assessment_tool_pip_packages:
    #       - '.'
    # yamllint enable rule:line-length

    - name: Install dirsearch and a requirements file in a venv
      # We do prepend the name of the role to the role variables, but
      # Molecule does its own role discovery with inconsistent naming.
      # This is the reason for the noqa below.
      ansible.builtin.include_role: # noqa var-naming[no-role-prefix]
        name: ansible-role-assessment-tool
      vars:
        assessment_tool_archive_src: https://github.com/maurosoria/dirsearch/tarball/master
        assessment_tool_install_dir: /tools/dirsearch
        assessment_tool_pip_requirements_file: requirements.txt
        assessment_tool_unarchive_extra_opts:
          - --strip-components=1

    - name: Install the mitm6 package in a venv
      # We do prepend the name of the role to the role variables, but
      # Molecule does its own role discovery with inconsistent naming.
      # This is the reason for the noqa below.
      ansible.builtin.include_role: # noqa var-naming[no-role-prefix]
        name: ansible-role-assessment-tool
      vars:
        assessment_tool_install_dir: /tools/mitm6
        assessment_tool_pip_packages:
          - mitm6
      tags:
        # Under Ubuntu 20 (Focal) and Python 3.8, the installation of
        # mitm6 is not idempotent.  Pip wants to re-install the
        # zope-interface package every time.  I believe this happens
        # only under Ubuntu 20 because it is a limitation of Python
        # 3.8; currently, Python 3.8.2 is the latest available for
        # Ubuntu 20:
        # https://packages.ubuntu.com/search?suite=focal&searchon=names&keywords=python3
        - molecule-idempotence-notest

    - name: Install the sqlmap tool
      # We do prepend the name of the role to the role variables, but
      # Molecule does its own role discovery with inconsistent naming.
      # This is the reason for the noqa below.
      ansible.builtin.include_role: # noqa var-naming[no-role-prefix]
        name: ansible-role-assessment-tool
      vars:
        assessment_tool_archive_src: https://github.com/sqlmapproject/sqlmap/tarball/master
        assessment_tool_install_dir: /tools/sqlmap
        assessment_tool_python: true
        assessment_tool_unarchive_extra_opts:
          - --strip-components=1
