---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-assessment-tool
      vars:
        archive_url: https://github.com/MacR6/sshenum/tarball/master
        install_dir: /tools/sshenum
        pip_packages:
          - paramiko
        python: yes
    - role: ansible-role-assessment-tool
      vars:
        archive_url: https://github.com/FortyNorthSecurity/Hasher/tarball/master
        install_dir: /tools/Hasher
        pip_packages:
          - '.'
        python: yes
